# Generated by Django 6.1.1 on 2026-09-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_packages_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
