# Generated by Django 6.1.1 on 2026-09-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_packages_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
