# Generated by Django 6.1.1 on 2026-09-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_packages_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
