# Generated by Django 6.1.1 on 2026-09-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wallet_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
