# Generated by Django 6.1.1 on 2026-09-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
