# Generated by Django 6.1.1 on 2026-09-20 14:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_account_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='referral_code',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
