# Generated by Django 6.1.1 on 2026-09-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
