# Generated by Django 6.1.1 on 2026-09-21 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userpackage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackage',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.packages'),
        ),
    ]
