# Generated by Django 6.1.1 on 2026-09-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackage',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
