# Generated by Django 6.1.1 on 2026-09-23 15:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_ledger_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='referral_reward',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='wallet_address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='wallet_type',
            field=models.CharField(default='USDT', max_length=50),
        ),
    ]
