# Generated by Django 6.1.1 on 2026-09-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_platformsettings_referral_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='packages',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
