# Generated by Django 6.1.1 on 2026-09-23 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_packages_max_amount_alter_packages_min_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoRate',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('usd_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
