# Generated by Django 6.1.1 on 2026-09-25 12:04

import django.db.models.deletion
from django.db import migrations, models


def copy_historical_investment_terms(apps, schema_editor):
    user_package = apps.get_model("core", "userPackage")
    for investment in user_package.objects.filter(package__isnull=False).iterator():
        package = investment.package
        investment.roi = package.roi
        investment.cycle = package.cycle
        investment.duration = package.duration
        investment.interval = package.interval
        investment.save(update_fields=["roi", "cycle", "duration", "interval"])


def populate_unique_deposit_hashes(apps, schema_editor):
    deposit = apps.get_model("core", "Deposit")
    seen = set()
    for item in deposit.objects.order_by("date_requested", "pk").iterator():
        normalized = (item.tx_hash or "").strip().upper()
        if not normalized or len(normalized) > 150 or normalized in seen:
            continue
        item.tx_hash_key = normalized
        item.save(update_fields=["tx_hash_key"])
        seen.add(normalized)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_cryptorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='tx_hash_key',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='cycle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.RunPython(copy_historical_investment_terms, migrations.RunPython.noop),
        migrations.RunPython(populate_unique_deposit_hashes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userpackage',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.packages'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='date_approved',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='InvestmentPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ROI', 'ROI'), ('PRINCIPAL', 'Principal')], max_length=9)),
                ('cycle_number', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='core.userpackage')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='investment_payout', to='core.transaction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('investment', 'kind', 'cycle_number'), name='unique_investment_payout')],
            },
        ),
    ]
