# Generated by Django 6.1.1 on 2026-09-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_account_user_alter_account_wallet_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
