# Generated by Django 6.1.1 on 2026-09-29 15:10

import django.db.models.deletion
from django.db import migrations, models


def seed_rails(apps, schema_editor):
    PaymentRail = apps.get_model("core", "PaymentRail")
    from core.rails import RAIL_CATALOG

    for order, (key, entry) in enumerate(RAIL_CATALOG.items()):
        PaymentRail.objects.update_or_create(
            key=key,
            defaults={
                "symbol": entry["symbol"],
                "network": entry["network"],
                "label": entry["label"],
                "is_active": False,
                "address": "",
                "min_deposit": None,
                "max_deposit": None,
                "min_withdraw": None,
                "max_withdraw": None,
                "display_order": order,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_withdrawal_date_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('network', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, default='', max_length=150)),
                ('min_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('min_withdraw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_withdraw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment rail',
                'verbose_name_plural': 'Payment rails',
                'ordering': ['display_order', 'key'],
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='amount_coin',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='rate_used',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='amount_coin',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='rate_used',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='preferred_rail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='core.paymentrail'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='rail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='core.paymentrail'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='rail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='core.paymentrail'),
        ),
        migrations.RunPython(seed_rails, migrations.RunPython.noop),
    ]
